// <auto-generated />
using System;
using OmniCache.IntegrationTests.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OmniCache.IntegrationTests.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OmniCache.IntegrationTests.Model.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int?>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("IsNewRelease")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("OmniCache.IntegrationTests.Model.RentalStore", b =>
                {
                    b.Property<string>("StoreCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.HasKey("StoreCode");

                    b.ToTable("RentalStores");
                });

            modelBuilder.Entity("OmniCache.IntegrationTests.Model.StoreStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("CopiesInStore")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyRentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<double>("OverdueFees")
                        .HasColumnType("double");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("TotalEarnings")
                        .HasColumnType("float");

                    b.Property<int>("TotalRentals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
