name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Show directory structure
      run: ls -R

    - name: Restore dependencies
      run: dotnet restore src/OmniCache.sln

    - name: Build
      run: dotnet build src/OmniCache.sln --no-restore

    - name: Test
      rrun: dotnet test src/OmniCache.sln --no-restore --verbosity normal

    - name: Publish OmniCache
      run: dotnet pack --no-build --configuration Release --output nupkgs /src/OmniCache/OmniCache.csproj
    - name: Publish OmniCache.EntityFramework
      run: dotnet pack --no-build --configuration Release --output nupkgs /src/OmniCache.EntityFramework/OmniCache.EntityFramework.csproj

    - name: Push to NuGet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: nupkgs/*.nupkg
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_COMMIT: true
        VERSION_REGEX: 'Version\s*(.*?)\s*'
        VERSION_STATIC: '1.0.0'
