name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Show directory structure
      run: ls -R

    - name: Restore dependencies
      run: dotnet restore src/OmniCache.sln

    - name: Build
      run: dotnet build src/OmniCache.sln --no-restore

    - name: Test
      run: dotnet test src/OmniCache.sln --no-restore --verbosity normal

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Pack OmniCache
      run: |
        dotnet build src/OmniCache/OmniCache.csproj -c Release -p:Version=${{ steps.get_version.outputs.VERSION }}
        dotnet pack src/OmniCache/OmniCache.csproj -c Release --no-build -o out /p:Version=${{ steps.get_version.outputs.VERSION }}

    - name: Pack OmniCache.EntityFramework
      run: |
        dotnet build src/OmniCache.EntityFramework/OmniCache.EntityFramework.csproj -c Release -p:Version=${{ steps.get_version.outputs.VERSION }}
        dotnet pack src/OmniCache.EntityFramework/OmniCache.EntityFramework.csproj -c Release --no-build -o out /p:Version=${{ steps.get_version.outputs.VERSION }}

    - name: Push to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
